---
exec_module: 'noop'
bilara_root_path: "~/bilara-data/root/pli/ms"

pali_canon_path: "~/ms_palicanon"
ms_yuttadhammo_path: ""
pali_concordance_filepath: "~/all_pali_concordance.json"

reference_root_path: "~/reference/pli/ms"

debug_dir: ""
# Log level: [0, 50]. 10-debug, 20-info
log_level: 20
